package com.yappyd.websocketservice.enums;

public enum WebSocketEventType {

    MESSAGE_CREATED,
    MESSAGE_UPDATED,
    MESSAGE_DELETED,

    CHAT_ACCESS_REVOKED,

    CHAT_CREATED,
    CHAT_UPDATED,
    CHAT_DELETED,

    CHAT_PARTICIPANT_ADDED,
    CHAT_PARTICIPANT_UPDATED,
    CHAT_PARTICIPANT_REMOVED,

    USER_PROFILE_UPDATED
}