CREATE DATABASE auth_db;
CREATE USER auth_user WITH PASSWORD :AUTH_PWD;

ALTER DATABASE auth_db OWNER TO auth_user;

\connect auth_db

GRANT USAGE, CREATE ON SCHEMA public TO auth_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO auth_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO auth_user;