CREATE DATABASE user_db;
CREATE USER user_user WITH PASSWORD :USER_PWD;

ALTER DATABASE user_db OWNER TO user_user;

\connect user_db

GRANT USAGE, CREATE ON SCHEMA public TO user_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO user_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO user_user;