CREATE DATABASE chat_db;
CREATE USER chat_user WITH PASSWORD :CHAT_PWD;

ALTER DATABASE chat_db OWNER TO chat_user;

\connect chat_db

GRANT USAGE, CREATE ON SCHEMA public TO chat_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO chat_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO chat_user;